name: Java CI with Maven

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Run tests with Maven
        env:
          TEST_COGNITO_USER_POOL_ID: ${{ secrets.TEST_COGNITO_USER_POOL_ID }}
          TEST_COGNITO_CLIENT_ID: ${{ secrets.TEST_COGNITO_CLIENT_ID }}
          TEST_COGNITO_USERNAME: ${{ secrets.TEST_COGNITO_USERNAME }}
          TEST_COGNITO_PASSWORD: ${{ secrets.TEST_COGNITO_PASSWORD }}
        run: mvn -B test --file pom.xml
